name: "Secure Coding Wargame"
description: "Turn every vulnerability into hands-on secure code learning labs."
author: "SecDim"
inputs:
  input_sarif_file:
    description: "Relative location of SARIF file to process"
    required: true
    default: "./findings.sarif"
  output_sarif_file:
    description: "Relative destination location for processed SARIF file"
    required: true
    default: "./findings.processed.sarif"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.input_sarif_file }}
    - ${{ inputs.output_sarif_file }}
branding:
  icon: "award"
  color: "blue"
