name: "SecDim Sandbox"
description: "Parses SARIF files and populates with links to relevant SecDim Sandboxes where you can explore and debug your security patch."
author: "SecDim"
inputs:
  input_sarif_file:
    description: "Relative location of SARIF file to process"
    required: true
    default: "./findings.sarif"
  output_sarif_file:
    description: "Relative destination location for processed SARIF file"
    required: true
    default: "./findings.processed.sarif"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.input_sarif_file }}
    - ${{ inputs.output_sarif_file }}
branding:
  icon: "box"
  color: "blue"
